const http = require('http');
const assert = require('assert');

const BASE_URL = 'http://localhost:5000/api';

function request(path, options = {}) {
  return new Promise((resolve, reject) => {
    const url = new URL(`${BASE_URL}${path}`);
    const reqOptions = {
      method: options.method || 'GET',
      hostname: url.hostname,
      port: url.port,
      path: url.pathname + url.search,
      headers: {
        'Content-Type': 'application/json',
        ...(options.headers || {}),
      },
    };

    const req = http.request(reqOptions, (res) => {
      let data = '';
      res.on('data', (chunk) => (data += chunk));
      res.on('end', () => {
        let parsed;
        try {
          parsed = JSON.parse(data);
        } catch (e) {
          parsed = data;
        }
        resolve({ status: res.statusCode, headers: res.headers, data: parsed });
      });
    });

    req.on('error', reject);

    if (options.body) {
      req.write(typeof options.body === 'string' ? options.body : JSON.stringify(options.body));
    }
    req.end();
  });
}

async function registerAndLogin(role, emailPrefix = 'user') {
  const email = `${emailPrefix}_${Date.now()}_${Math.floor(Math.random() * 10000)}@example.com`;
  const password = 'Password123!';
  const name = `${role} User`;

  const regRes = await request('/auth/register', {
    method: 'POST',
    body: { name, email, password, role },
  });

  if (regRes.status !== 201 && regRes.status !== 200) {
    throw new Error(`Registration failed for ${email}: ${JSON.stringify(regRes.data)}`);
  }

  const loginRes = await request('/auth/login', {
    method: 'POST',
    body: { email, password },
  });

  if (loginRes.status !== 200) {
    throw new Error(`Login failed for ${email}: ${JSON.stringify(loginRes.data)}`);
  }

  return {
    userId: loginRes.data.user.id || loginRes.data.user._id,
    token: loginRes.data.token,
    user: loginRes.data.user,
  };
}

async function runTests() {
  console.log('============================================================');
  console.log('STARTING DEVELOPER MY STARTUPS & WORKSPACE VERIFICATION SUITE');
  console.log('============================================================\n');

  let passed = 0;
  let failed = 0;

  async function test(title, fn) {
    try {
      await fn();
      console.log(`[PASS] ${title}`);
      passed++;
    } catch (err) {
      console.error(`[FAIL] ${title}`);
      console.error(`       Error: ${err.message}`);
      failed++;
    }
  }

  // Setup test entities
  console.log('--- Setting up test accounts and startups ---');
  const founderA = await registerAndLogin('FOUNDER', 'founderA');
  const founderB = await registerAndLogin('FOUNDER', 'founderB');
  const developerA = await registerAndLogin('DEVELOPER', 'devA');
  const developerB = await registerAndLogin('DEVELOPER', 'devB');
  const investor = await registerAndLogin('INVESTOR', 'investor');

  // Create Startup A (AgriVision AI)
  const createStartupARes = await request('/startups', {
    method: 'POST',
    headers: { Authorization: `Bearer ${founderA.token}` },
    body: {
      name: 'AgriVision AI',
      tagline: 'AI-powered crop disease detection',
      problemStatement: 'Farmers lose 30% yield to undetected early-stage fungal crop blights.',
      solution: 'Computer vision drone and mobile app scanning foliage with real-time pesticide guidance.',
      industry: 'Agriculture',
      stage: 'MVP',
      description: 'A deep-tech agricultural intelligence platform.',
    },
  });
  const startupAId = createStartupARes.data.startup.id || createStartupARes.data.startup._id;

  // Create Startup B (HealthTrack)
  const createStartupBRes = await request('/startups', {
    method: 'POST',
    headers: { Authorization: `Bearer ${founderB.token}` },
    body: {
      name: 'HealthTrack',
      tagline: 'Predictive patient vital anomaly alerting',
      problemStatement: 'ICU nurse fatigue results in delayed intervention for cardiac distress.',
      solution: 'Continuous ECG wearable with on-device edge ML anomaly alerts.',
      industry: 'Healthcare',
      stage: 'MVP',
      description: 'Continuous vital telemetry platform.',
    },
  });
  const startupBId = createStartupBRes.data.startup.id || createStartupBRes.data.startup._id;

  // Create Startup C (EduFlow)
  const createStartupCRes = await request('/startups', {
    method: 'POST',
    headers: { Authorization: `Bearer ${founderA.token}` },
    body: {
      name: 'EduFlow',
      tagline: 'Adaptive AI learning journeys',
      problemStatement: 'Static curriculum leaves 45% of students behind in foundational STEM concepts.',
      solution: 'Dynamic mastery-based lesson tree generated by fine-tuned LLMs.',
      industry: 'EdTech',
      stage: 'IDEA',
      description: 'Personalized STEM tutoring system.',
    },
  });
  const startupCId = createStartupCRes.data.startup.id || createStartupCRes.data.startup._id;

  console.log(`Startup A: ${startupAId} (AgriVision AI)`);
  console.log(`Startup B: ${startupBId} (HealthTrack)`);
  console.log(`Startup C: ${startupCId} (EduFlow)\n`);

  console.log('--- Executing Verification Points 1 to 12 ---');

  // TEST 1: Developer A requests Startup A, Founder A accepts -> Startup A appears in Developer A's My Startups
  await test('TEST 1: Developer receives Startup A in My Startups upon founder accept', async () => {
    // 1. Submit join request
    const reqRes = await request(`/join-requests/${startupAId}`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${developerA.token}` },
      body: { message: 'I want to build React and Node.js components for AgriVision AI' },
    });
    assert.strictEqual(reqRes.status, 201, 'Request to join should return 201');
    const requestId = reqRes.data.request.id;

    // 2. Founder accepts
    const acceptRes = await request(`/join-requests/${requestId}/accept`, {
      method: 'PUT',
      headers: { Authorization: `Bearer ${founderA.token}` },
    });
    assert.strictEqual(acceptRes.status, 200, 'Accept should return 200');

    // 3. Developer calls GET /api/developers/my-startups
    const myStartupsRes = await request('/developers/my-startups', {
      method: 'GET',
      headers: { Authorization: `Bearer ${developerA.token}` },
    });
    assert.strictEqual(myStartupsRes.status, 200, 'GET /my-startups should return 200');
    assert.strictEqual(myStartupsRes.data.success, true);
    assert(Array.isArray(myStartupsRes.data.startups), 'Should return startups array');

    const found = myStartupsRes.data.startups.find((s) => s.id === startupAId || s._id === startupAId);
    assert(found, 'Startup A must appear in Developer A My Startups');
    assert.strictEqual(found.name, 'AgriVision AI');
    assert.strictEqual(found.role, 'DEVELOPER');
    assert(found.teamSize >= 2, 'teamSize should count founder + developer');
  });

  // TEST 2: Status discrimination (PENDING or REJECTED must NOT appear)
  await test('TEST 2: PENDING and REJECTED startups do NOT appear in My Startups', async () => {
    // Developer A requests Startup B -> leaves it PENDING
    const reqB = await request(`/join-requests/${startupBId}`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${developerA.token}` },
      body: { message: 'I want to help with HealthTrack' },
    });
    assert.strictEqual(reqB.status, 201);

    // Developer A requests Startup C -> Founder A rejects it
    const reqC = await request(`/join-requests/${startupCId}`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${developerA.token}` },
      body: { message: 'I want to help with EduFlow' },
    });
    assert.strictEqual(reqC.status, 201);
    const rejectRes = await request(`/join-requests/${reqC.data.request.id}/reject`, {
      method: 'PUT',
      headers: { Authorization: `Bearer ${founderA.token}` },
    });
    assert.strictEqual(rejectRes.status, 200);

    // Query Developer A's My Startups: should ONLY have Startup A, NOT B and NOT C
    const myStartupsRes = await request('/developers/my-startups', {
      method: 'GET',
      headers: { Authorization: `Bearer ${developerA.token}` },
    });
    assert.strictEqual(myStartupsRes.status, 200);
    const ids = myStartupsRes.data.startups.map((s) => s.id || s._id);
    assert(ids.includes(startupAId), 'Startup A must be included');
    assert(!ids.includes(startupBId), 'Startup B (PENDING) must NOT be included');
    assert(!ids.includes(startupCId), 'Startup C (REJECTED) must NOT be included');
  });

  // TEST 3: Multiple startups membership & context isolation
  await test('TEST 3: Developer belonging to multiple startups has isolated workspace context', async () => {
    // Now Founder B accepts Developer A for Startup B
    const founderBRequests = await request(`/startups/${startupBId}/join-requests`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${founderB.token}` },
    });
    const pendingReqB = founderBRequests.data.requests.find((r) => r.status === 'PENDING');
    await request(`/join-requests/${pendingReqB.id}/accept`, {
      method: 'PUT',
      headers: { Authorization: `Bearer ${founderB.token}` },
    });

    // Create task in Startup A
    const taskARes = await request(`/startups/${startupAId}/tasks`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${founderA.token}` },
      body: {
        title: 'Implement drone image upload API',
        description: 'Multi-part S3 upload endpoint for drone camera frames',
        status: 'TODO',
        priority: 'HIGH',
        assignedTo: developerA.userId,
      },
    });
    assert.strictEqual(taskARes.status, 201);

    // Create task in Startup B
    const taskBRes = await request(`/startups/${startupBId}/tasks`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${founderB.token}` },
      body: {
        title: 'Bluetooth Low Energy telemetry parser',
        description: 'Parse raw hex bytes from wearable ECG patch',
        status: 'IN_PROGRESS',
        priority: 'HIGH',
        assignedTo: developerA.userId,
      },
    });
    assert.strictEqual(taskBRes.status, 201);

    // Fetch Startup A workspace
    const wsA = await request(`/developers/startups/${startupAId}`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${developerA.token}` },
    });
    assert.strictEqual(wsA.status, 200);
    assert.strictEqual(wsA.data.startup.name, 'AgriVision AI');

    // Fetch Startup B workspace
    const wsB = await request(`/developers/startups/${startupBId}`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${developerA.token}` },
    });
    assert.strictEqual(wsB.status, 200);
    assert.strictEqual(wsB.data.startup.name, 'HealthTrack');

    // Verify task isolation on task endpoint
    const tasksA = await request(`/startups/${startupAId}/tasks`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${developerA.token}` },
    });
    const titlesA = tasksA.data.data.map((t) => t.title);
    assert(titlesA.includes('Implement drone image upload API'));
    assert(!titlesA.includes('Bluetooth Low Energy telemetry parser'), 'Startup A must not leak Startup B tasks');
  });

  // TEST 4: Non-member developer cannot access developer workspace (403)
  await test('TEST 4: Developer cannot access workspace of unjoined startup (403 Forbidden)', async () => {
    // Developer B has not joined Startup A
    const wsRes = await request(`/developers/startups/${startupAId}`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${developerB.token}` },
    });
    assert.strictEqual(wsRes.status, 403, 'Should return 403 Forbidden for non-member developer');
  });

  // TEST 5: Developer opens My Tasks and views assigned items
  let testTaskId = null;
  await test('TEST 5: Developer views assigned tasks correctly', async () => {
    const tasksRes = await request(`/startups/${startupAId}/tasks`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${developerA.token}` },
    });
    assert.strictEqual(tasksRes.status, 200);
    const myTask = tasksRes.data.data.find(
      (t) => (t.assignedTo?._id || t.assignedTo)?.toString() === developerA.userId
    );
    assert(myTask, 'Assigned task must be present');
    assert.strictEqual(myTask.title, 'Implement drone image upload API');
    testTaskId = myTask._id || myTask.id;
  });

  // TEST 6: Developer updates task status (TODO -> IN_PROGRESS -> DONE) and persists
  await test('TEST 6: Developer updates task status and change persists in MongoDB', async () => {
    assert(testTaskId, 'testTaskId must be defined');

    // Update to IN_PROGRESS
    const update1 = await request(`/tasks/${testTaskId}`, {
      method: 'PUT',
      headers: { Authorization: `Bearer ${developerA.token}` },
      body: { status: 'IN_PROGRESS' },
    });
    assert.strictEqual(update1.status, 200);
    assert.strictEqual(update1.data.data.status, 'IN_PROGRESS');

    // Update to DONE
    const update2 = await request(`/tasks/${testTaskId}`, {
      method: 'PUT',
      headers: { Authorization: `Bearer ${developerA.token}` },
      body: { status: 'DONE' },
    });
    assert.strictEqual(update2.status, 200);
    assert.strictEqual(update2.data.data.status, 'DONE');

    // Fetch tasks again to verify database persistence
    const verifyTasks = await request(`/startups/${startupAId}/tasks`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${developerA.token}` },
    });
    const refreshedTask = verifyTasks.data.data.find((t) => (t._id || t.id) === testTaskId);
    assert.strictEqual(refreshedTask.status, 'DONE', 'Task status must persist as DONE');
  });

  // TEST 7: Developer queries AI Mentor for guidance grounded in startup context
  await test('TEST 7: Developer AI Mentor returns context-grounded guidance', async () => {
    // Add a high priority task so mentor has priority guidance to offer
    await request(`/startups/${startupAId}/tasks`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${founderA.token}` },
      body: {
        title: 'Offline crop leaf bounding-box inference',
        description: 'Run lightweight quantized ONNX model without mobile data',
        status: 'TODO',
        priority: 'HIGH',
        assignedTo: developerA.userId,
      },
    });

    const mentorRes = await request(`/developers/startups/${startupAId}/ai-mentor`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${developerA.token}` },
      body: { message: 'What should I work on next?' },
    });

    assert.strictEqual(mentorRes.status, 200, 'Developer AI Mentor should return 200');
    assert.strictEqual(mentorRes.data.success, true);
    assert(typeof mentorRes.data.answer === 'string' && mentorRes.data.answer.length > 0);
    assert(Array.isArray(mentorRes.data.actions), 'Should include actions array');
    assert(
      mentorRes.data.answer.toLowerCase().includes('agrivision') ||
      mentorRes.data.answer.toLowerCase().includes('inference') ||
      mentorRes.data.answer.toLowerCase().includes('priority') ||
      mentorRes.data.answer.toLowerCase().includes('task')
    );
  });

  // TEST 8: Developer cannot perform founder-only operations (403)
  await test('TEST 8: Developer receives 403 when attempting founder-only operations', async () => {
    // 1. Cannot add financial transaction
    const finRes = await request(`/finance/${startupAId}/transactions`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${developerA.token}` },
      body: { type: 'EXPENSE', amount: 5000, category: 'INFRASTRUCTURE', description: 'Server' },
    });
    assert.strictEqual(finRes.status, 403, 'Developer cannot add finance transactions (403)');

    // 2. Cannot update startup ownership / basic info
    const updateStartupRes = await request(`/startups/${startupAId}`, {
      method: 'PUT',
      headers: { Authorization: `Bearer ${developerA.token}` },
      body: { name: 'Hacked AgriVision' },
    });
    assert.strictEqual(updateStartupRes.status, 403, 'Developer cannot update startup info (403)');

    // 3. Cannot view founder join requests endpoint directly
    const founderRequestsRes = await request(`/startups/${startupAId}/join-requests`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${developerA.token}` },
    });
    assert.strictEqual(founderRequestsRes.status, 403, 'Developer cannot access founder join-requests endpoint (403)');

    // 4. Cannot generate pitch deck
    const pitchRes = await request(`/ai/pitch/${startupAId}`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${developerA.token}` },
    });
    assert.strictEqual(pitchRes.status, 403, 'Developer cannot generate pitch deck (403)');
  });

  // TEST 9: Developer AI Mentor forbids non-member developer (403)
  await test('TEST 9: Non-member developer cannot access AI Mentor (403 Forbidden)', async () => {
    const deniedMentorRes = await request(`/developers/startups/${startupAId}/ai-mentor`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${developerB.token}` },
      body: { message: 'What should I do?' },
    });
    assert.strictEqual(deniedMentorRes.status, 403, 'Non-member developer must be denied AI Mentor (403)');
  });

  // TEST 10: Empty state for developer with no joined startups
  await test('TEST 10: Fresh developer with zero joined startups receives empty array', async () => {
    const emptyDev = await registerAndLogin('DEVELOPER', 'freshDev');
    const emptyRes = await request('/developers/my-startups', {
      method: 'GET',
      headers: { Authorization: `Bearer ${emptyDev.token}` },
    });
    assert.strictEqual(emptyRes.status, 200);
    assert.strictEqual(emptyRes.data.success, true);
    assert(Array.isArray(emptyRes.data.startups) && emptyRes.data.startups.length === 0);
  });

  // TEST 11: Unauthenticated request returns 401
  await test('TEST 11: Unauthenticated request returns 401', async () => {
    const unauthRes = await request('/developers/my-startups', { method: 'GET' });
    assert.strictEqual(unauthRes.status, 401, 'Unauthenticated request must return 401');
  });

  // TEST 12: Investor cannot access developer workspace or developer my-startups (403)
  await test('TEST 12: Investor role cannot access developer workspace (403)', async () => {
    const invMyStartupsRes = await request('/developers/my-startups', {
      method: 'GET',
      headers: { Authorization: `Bearer ${investor.token}` },
    });
    assert.strictEqual(invMyStartupsRes.status, 403, 'Investor cannot access /api/developers/my-startups (403)');

    const invWsRes = await request(`/developers/startups/${startupAId}`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${investor.token}` },
    });
    assert.strictEqual(invWsRes.status, 403, 'Investor cannot access developer workspace (403)');
  });

  console.log('\n============================================================');
  console.log(`SUMMARY: ${passed} PASSED, ${failed} FAILED (TOTAL: ${passed + failed})`);
  console.log('============================================================\n');

  if (failed > 0) {
    process.exit(1);
  }
}

runTests().catch((err) => {
  console.error('Fatal test runner error:', err);
  process.exit(1);
});
